events {}

http {

  upstream pedidos {
    server pedidos-service:8080;
  }

  upstream pagamentos {
    server pagamentos-service:8080;
  }

  upstream estoque {
    server estoque-service:8080;
  }

  server {

    listen 80;

    location /pedidos {
      proxy_pass http://pedidos;
    }

    location /pagamentos {
      proxy_pass http://pagamentos;
    }

    location /estoque {
      proxy_pass http://estoque;
    }
  }
}